
# To install gsl (inside container)
# docker exec -it container_name /bin/bash
RUN apt-get install libgsl-dev

# To install clang
#add add-apt-repository
apt-get install software-properties-common  

# add apt-transport-https
apt-get install apt-transport-https

# to install latest versionn
bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"

# Alternatively - grossly outdated version
sudo apt-get update
sudo apt-get install clang

# to install the gdb debugger (gcc)
sudo apt-get install gdb

# to install subbotools from source
# download the tar package in a temp directory
wget -P /tmp/ ftp://cafed.sssup.it/packages/subbotools-1.3.0.tar.gz
cd /tmp
tar xvzf subbotools-1.3.0.tar.gz
cd subbotools-1.3.0
./configure
make
make install
