# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

varcovar <- function(par, N, dim) {
    .Call(`_Rsubbotools_varcovar`, par, N, dim)
}

sortRcpp <- function(x) {
    invisible(.Call(`_Rsubbotools_sortRcpp`, x))
}

#' subbofit
#' Fit a power exponential density via maximum likelihood
#' 
#'   Verbosity levels:
#'   0 just the final ouput
#'   1 the results of intermediate steps
#'   2 internal information on intermediate steps
#'   3 gory details on intermediate steps
#' 
#' Fit symmetric power exponential density. Read from files of from standard input 
#' Usage: %s [options] [files]                                                     
#' Options:                                                                       
#'  -O  output type (default 0)                
#'       0  parameter b a m and log-likelihood   
#'       1  the estimated distribution function computed on the provided points     
#'       2  the estimated density function computed on the provided points 
#'       3  parameters b a m and their standard errors 
#'  -x  set initial conditions b, a,m  (default 2, 1,0)
#'  -m  the mode is not estimated but is set to the value provided
#'  -s  number of intervals to explore at each iteration (default 10)
#'  -V  verbosity level (default 0)           
#'       0  just the final result        
#'       1  headings and summary table   
#'       2  intermediate steps results   
#'       3  intermediate steps internals 
#'       4+  details of optim. routine   
#'  -M  active estimation steps. The value is the sum of (default 7)
#'       1  initial estimation based on method of moments
#'       2  global optimization not considering lack of smoothness in m
#'       4  local optimization taking non-smoothness in m into consideration 
#'  -G  set global optimization options. Fields are step, tol, iter, eps, msize, algo.
#'      Empty field implies default (default .1, 1e-2, 100, 1e-3, 1e-5, 3)
#'  -I  set local optimization options. Fields are step, tol, iter, eps, msize, algo.
#'      Empty field implies default (default .01, 1e-4, 200, 1e-4, 1e-5, 5)
#' The optimization parameters are
#'  step  initial step size of the searching algorithm                  
#'  tol  line search tolerance iter: maximum number of iterations      
#'  eps  gradient tolerance : stopping criteria ||gradient||<eps       
#'  msize  simplex max size : stopping criteria ||max edge||<msize     
#'  algo  optimization methods:
#'          0 Fletcher-Reeves
#'          1 Polak-Ribiere     
#'          2 Broyden-Fletcher-Goldfarb-Shanno
#'          3 Steepest descent           
#'          4 Nelder-Mead simplex
#'          5 Broyden-Fletcher-Goldfarb-Shanno ver.2
#' 
#' Examples:
#'  'subbofit -m 1 -M 6 <file'  estimate a and b with m = 1 and skipping initial  
#'                              method of moments estimation
#'
#' methods of estimation
#' 0 - no minimization
#' 1 - method of moments
#' 2 - global optimization
#' 4 - interval optimization
#' interv_step number of intervals to expose 
#' interv_step number of intervals to expose 
#' par - par[0] = b par[1] = a par[2] = m */
#' itv_opt_par - interval optimization parameters */
subbofit <- function(data, verb = 0L, method = 7L, interv_step = 10L, output = 0L, provided_m_ = NULL, par = as.numeric( c(2.,1.,0.)), g_opt_par = as.numeric( c(.1, 1e-2, 100, 1e-3, 1e-5, 3,0)), itv_opt_par = as.numeric( c(.01, 1e-3, 200, 1e-3, 1e-5, 5,0))) {
    .Call(`_Rsubbotools_subbofit`, data, verb, method, interv_step, output, provided_m_, par, g_opt_par, itv_opt_par)
}

